[package]
name = "nannou-laser-cuda"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
bevy = { version = "0.19.0", default-features = false }
image = "0.25"
nannou = { version = "0.20.0", features = ["video"] }
cuda-async = { path = "../../crates/cuda-oxide/crates/cuda-async" }
cuda-core = { path = "../../crates/cuda-oxide/crates/cuda-core" }
cuda-device = { path = "../../crates/cuda-oxide/crates/cuda-device" }
cuda-host = { path = "../../crates/cuda-oxide/crates/cuda-host" }
nannou_laser = "0.20.0"
